import type { NextConfig } from "next";
import path from "node:path";

const monorepoRoot = path.resolve(__dirname, "..");
const contractsDir = path.resolve(monorepoRoot, "contracts");

const nextConfig: NextConfig = {
  turbopack: {
    root: monorepoRoot,
    resolveAlias: {
      // contracts/deployments/*.json — deployed addresses (updated on each redeploy)
      "@deployments": path.resolve(contractsDir, "deployments"),
      // contracts/artifacts/ — compiled ABIs (generated by `hardhat compile`)
      "@artifacts": path.resolve(contractsDir, "artifacts"),
    },
  },
};

export default nextConfig;
